title: Code Drop
description: "Dumping me PowerShell brilliance, smegheads! Sharing code and me smarts for an epic dose of scripting adventure. Get ready to power up your code!"
theme: minima
header_pages:
   - about.md
